"""Initial migration

Revision ID: bdb6de4e9dfe
Revises: 
Create Date: 2025-12-09 12:15:26.452347

"""
from typing import Sequence, Union

# Se importa sqlmodel para que se pueda usar en el script
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb6de4e9dfe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_label_owner_link')
    )
    op.create_index(op.f('ix_label_name'), 'label', ['name'], unique=False)
    op.create_index(op.f('ix_label_owner_id'), 'label', ['owner_id'], unique=False)
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_owner_id'), 'note', ['owner_id'], unique=False)
    op.create_table('labelshare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('READ', 'EDIT', 'DELETE', name='sharerole'), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_id', 'user_id', name='uq_label_user')
    )
    op.create_index(op.f('ix_labelshare_label_id'), 'labelshare', ['label_id'], unique=False)
    op.create_index(op.f('ix_labelshare_user_id'), 'labelshare', ['user_id'], unique=False)
    op.create_table('notelabellink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'label_id', name='uq_note_label_link')
    )
    op.create_index(op.f('ix_notelabellink_label_id'), 'notelabellink', ['label_id'], unique=False)
    op.create_index(op.f('ix_notelabellink_note_id'), 'notelabellink', ['note_id'], unique=False)
    op.create_table('noteshare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('READ', 'EDIT', 'DELETE', name='sharerole'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'user_id', name='uq_note_user')
    )
    op.create_index(op.f('ix_noteshare_note_id'), 'noteshare', ['note_id'], unique=False)
    op.create_index(op.f('ix_noteshare_user_id'), 'noteshare', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_noteshare_user_id'), table_name='noteshare')
    op.drop_index(op.f('ix_noteshare_note_id'), table_name='noteshare')
    op.drop_table('noteshare')
    op.drop_index(op.f('ix_notelabellink_note_id'), table_name='notelabellink')
    op.drop_index(op.f('ix_notelabellink_label_id'), table_name='notelabellink')
    op.drop_table('notelabellink')
    op.drop_index(op.f('ix_labelshare_user_id'), table_name='labelshare')
    op.drop_index(op.f('ix_labelshare_label_id'), table_name='labelshare')
    op.drop_table('labelshare')
    op.drop_index(op.f('ix_note_owner_id'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_label_owner_id'), table_name='label')
    op.drop_index(op.f('ix_label_name'), table_name='label')
    op.drop_table('label')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
